name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  unit:
    name: Compile
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [8]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - run: git fetch --tags || true
      - run: sbt +publishLocal
